### ISSUE TITLE
Reversing the icon names between light and dark

### ISSUE THREAD

**Issue by Aiyon860** [xandemon/developer-icons#20]
![Screenshot 2024-12-05 163332](https://github.com/user-attachments/assets/2f113b34-639e-4d43-985a-0cb42ab25176)

Hello,

I noticed a small typo on your website. The icon for the Rust language has a caption labeled as Rust light, but the image of the icon is dark.

**Comment by xandemon** [comment]
Hi @Aiyon860 , thanks for reporting! That was kind of intentional since you need a light-themed icon to use in any dark-themed site which led to me naming like this. For eg: `Rust Dark` --> Rust icon for dark-themed sites and vice-versa.
But now that you mentioned it, it does look confusing. Maybe I should change that?

**Comment by xandemon** [comment]
### Issue: Confusing Icon Naming System  

As pointed out by @Aiyon860, the current naming system for icons is confusing. For instance:  
- A **dark icon** is labeled as *Rust Light*.  
- A **light icon** is labeled as *Rust Dark*.  

This inconsistency applies to most of the icons.  

#### Proposed Fix  
- Update the naming convention in `/lib/iconsData.ts` to reflect the actual icon type:  
  - Use **`Light`** for light-themed icons.  
  - Use **`Dark`** for dark-themed icons.  

#### How to Contribute  
This task involves renaming the icon labels in the mentioned file. If you're interested in sending a PR for this, please leave a comment below.  
If no one picks this up, I’ll take this task myself.  

Feel free to reach out if you have any questions or need assistance and of course, you can find proper [contributing guide here](https://xandemon.github.io/developer-icons/docs/contributing/)!

**Comment by roshan-Kawale** [comment]
I’d like to take on this issue and update the naming convention in /lib/iconsData.ts to ensure consistency between the icon labels and their themes. Could you please assign this issue to me?

**Comment by xandemon** [comment]
Great! I'm assigning it to you then. Feel free to ask if you need any help.
