### ISSUE TITLE
Missing Angular Icon

### ISSUE THREAD

**Issue by scottwalter-nice** [xandemon/developer-icons#27]
Can you please add an icon for the Angular framework.

**Comment by xandemon** [comment]
Thanks for reporting the missing Angular icon, @scottwalter-nice ! Will add that icon today and update the package.

> #### How to Contribute  
> If you're interested in sending a PR for this, please leave a comment below.  
> If no one picks this up, I’ll handle the task myself.  
> 
> Feel free to reach out if you have any questions or need assistance and of course, you can find proper [contributing guide here](https://xandemon.github.io/developer-icons/docs/contributing/)!

**Comment by ChinoUkaegbu** [comment]
Hi, I'd like to pick this up!
